---
apiVersion: v1
kind: Secret
metadata:
  name: jdafda-123-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/jdafda-123-gateway-gitops
